# Generated by Django 5.0.2 on 2024-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
